import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import emojiCodePoints from '@unicode/unicode-17.0.0/Binary_Property/Emoji/code-points.js';
import unicodeNames from '@unicode/unicode-17.0.0/Names/index.js';

const DIRECT_SHORTCODE_ALIASES = {
  '+1': '👍',
  '-1': '👎',
  clapping: '👏',
  grin: '😁',
  heart: '❤️',
  laughing: '😆',
  ok_hand: '👌',
  pray: '🙏',
  rofl: '🤣',
  smile: '😄',
  smiley: '😃',
  sob: '😭',
  tada: '🎉',
  thumbsdown: '👎',
  thumbsup: '👍',
  wave: '👋',
};

const SHORTCODE_SYNONYMS = {
  grinning: 'grinning_face',
  heart_eyes: 'smiling_face_with_heart_shaped_eyes',
  joy: 'face_with_tears_of_joy',
  neutral_face: 'neutral_face',
  open_mouth: 'face_with_open_mouth',
  pensive: 'pensive_face',
  perspiring_face: 'anxious_face_with_sweat',
  scream: 'face_screaming_in_fear',
  simple_smile: 'slightly_smiling_face',
  thinking: 'thinking_face',
  thumbs_down: 'thumbs_down_sign',
  thumbs_up: 'thumbs_up_sign',
  worried: 'worried_face',
};

function normalizeShortcode(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_+\-\s]/g, '')
    .replace(/[-\s]+/g, '_')
    .replace(/_+/g, '_');
}

function normalizeUnicodeName(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/[\s-]+/g, '_');
}

const shortcodeMap = new Map();

for (const codePoint of emojiCodePoints) {
  const name = unicodeNames.get(codePoint);
  if (!name) continue;

  const shortcode = normalizeUnicodeName(name);
  if (!shortcode) continue;

  if (!shortcodeMap.has(shortcode)) {
    shortcodeMap.set(shortcode, String.fromCodePoint(codePoint));
  }
}

for (const [alias, unicode] of Object.entries(DIRECT_SHORTCODE_ALIASES)) {
  shortcodeMap.set(normalizeShortcode(alias), unicode);
}

for (const [alias, canonical] of Object.entries(SHORTCODE_SYNONYMS)) {
  const canonicalUnicode = shortcodeMap.get(normalizeShortcode(canonical));
  if (canonicalUnicode) {
    shortcodeMap.set(normalizeShortcode(alias), canonicalUnicode);
  }
}

const sortedEntries = [...shortcodeMap.entries()].sort(([a], [b]) => a.localeCompare(b));
const objectLiteral = JSON.stringify(Object.fromEntries(sortedEntries), null, 2);

const output = `/* Auto-generated by scripts/generateEmojiMap.mjs */\nexport const EMOJI_SHORTCODE_MAP: Record<string, string> = ${objectLiteral};\n`;

const target = resolve('src/generated/emojiMap.ts');
writeFileSync(target, output, 'utf8');

console.log(`Generated ${sortedEntries.length} entries to ${target}`);
